name: 📄 Check licenses

on:
  push:
    branches:
      - main
    paths:
      - "requirements-dev.lock"
      - ".github/workflows/check-licenses.yml"

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          sed '/-e/d' requirements-dev.lock > requirements.txt
          pip install --no-cache-dir -r requirements.txt

      - name: Install dependencies for sample-project
        run: |
          python3 scripts/generate_requirements.py
          pip install --no-cache-dir -r requirements.txt
        env:
          LOCK_FILE_PATH: "pipenv-project/Pipfile.lock"
        shell: bash

      - name: Install pip-licenses
        run: pip install pip-licenses

      - name: Show list of installed packages
        run: pip-licenses --order=license

      - name: Run Licenses Check
        run: >
          pip-licenses
          --allow-only="
            Apache Software License;
            MIT License;
            BSD License;
            Python Software Foundation License;
            The Unlicense (Unlicense);"
          --ignore-packages
            python-mutation-report
