name: e2e-test

on:
  workflow_call:
    inputs:
      hosted-runner-name:
        required: true
        type: string
jobs:
  e2e-test:
    runs-on: ${{ inputs.hosted-runner-name }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create and checkout new branch
        run: |
          rm -rf pipenv-project ; mkdir pipenv-project;
          cp -r development/pipenv-project-to-replace/* pipenv-project

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pipenv-project
          git commit -m "Auto commit by GitHub Actions"
          git log --oneline -n 5

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Mutaion report
        uses: ./
        with:
          lock-file-path: "pipenv-project/Pipfile.lock"
          src-directory: "pipenv-project/src"
          test-directory: "pipenv-project/tests"
          where-to-run-test: "pipenv-project"

      - name: Revert last commit
        run: git reset --hard HEAD~1

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          force: true

      - run: git log --oneline -n 5

      - name: Get PR comment
        env:
          GITHUB_TOKEN: ${{ github.token }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr view "${URL}" --json comments | jq '.comments[-1].body' > actual_PR_comment.txt

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compare PR comment
        run: python3 tests/e2e/compare_PR_comment.py
