name: 🧪 Test this repository actions

on: [workflow_dispatch, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test mutation report action
    permissions:
      pull-requests: write

    steps:
      - id: foo
        uses: ./
        with:
          lock_file_path: "pipenv-project/Pipfile.lock"
          src_directory: "pipenv-project/src"
          test_directory: "pipenv-project/tests"
