name: 🧪 Test this repository actions

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test mutation report action
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./
        with:
          lock_file_path: "pipenv-project/Pipfile.lock"
