name: 🧪 Test this repository actions on PR

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test mutation report action
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - id: foo
        uses: ./
        with:
          lock-file-path: "pipenv-project/Pipfile.lock"
          src-directory: "pipenv-project/src"
          test-directory: "pipenv-project/tests"

      - name: Debug of artifact
        uses: actions/upload-artifact@v4
        with:
          name: temporary
          path: temporary
