name: 🧪 Test this repository actions in pipenv-project

on:
  pull_request:
    paths:
      - "pipenv-project/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-mutation-report-action:
    runs-on: ubuntu-latest
    name: Test mutation report action
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          lock-file-path: "pipenv-project/Pipfile.lock"
          src-directory: "pipenv-project/src"
          test-directory: "pipenv-project/tests"
          where-to-run-test: "pipenv-project"

      - uses: actions/upload-artifact@v4
        with:
          name: temporary-pipenv-project
          path: |
            temporary
            pipenv-project
          retention-days: 5
