name: 🧪 Test this repository actions on PR

on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test mutation report actionsaa
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - id: foo
        uses: ./
        with:
          lock-file-path: "pipenv-project/Pipfile.lock"
          src-directory: "pipenv-project/src"
          test-directory: "pipenv-project/tests"
