name: 🧪 Automated ubuntu and macos unit test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  file-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    outputs:
      execute-unit-test: ${{ steps.filter.outputs.unit-test }}
      execute-e2e-test: ${{ steps.filter.outputs.e2e-test }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            unit-test:
              - scripts/**
              - pipenv-project/**
              - tests/**
              - Pipfile
              - Pipfile.lock
              - .github/workflows/unit-test.yml
              - .github/workflows/ubuntu-and-macos-test.yml
            e2e-test:
              - scripts/**
              - pipenv-project/**
              - development/pipenv-project-to-replace/**
              - action.yml
              - requirements.lock
              - tests/data/expected/PR_comment.txt
              - .github/workflows/e2e-test.yml
              - .github/workflows/ubuntu-and-macos-test.yml

  ubuntu-unit-test:
    name: ubuntu unit
    needs: [file-changes]
    if: needs.file-changes.outputs.execute-unit-test == 'true'
    uses: ./.github/workflows/unit-test.yml
    with:
      hosted-runner-name: ubuntu-latest

  macos-unit-test:
    name: macos unit
    needs: [file-changes]
    if: needs.file-changes.outputs.execute-unit-test == 'true'
    uses: ./.github/workflows/unit-test.yml
    with:
      hosted-runner-name: macos-latest

  ubuntu-e2e-test:
    name: ubuntu e2e
    permissions:
      contents: write
      pull-requests: write
    needs: [file-changes, ubuntu-unit-test, macos-unit-test]
    if: always() && needs.file-changes.outputs.execute-e2e-test == 'true'
    uses: ./.github/workflows/e2e-test.yml
    with:
      hosted-runner-name: ubuntu-latest

  macos-e2e-test:
    name: macos e2e
    permissions:
      contents: write
      pull-requests: write
    needs: [file-changes, ubuntu-e2e-test]
    if: always() && needs.ubuntu-e2e-test.result == 'success'
    uses: ./.github/workflows/e2e-test.yml
    with:
      hosted-runner-name: macos-latest

  status-check:
    name: acceptance test passed
    needs: [ubuntu-unit-test, macos-unit-test, ubuntu-e2e-test, macos-e2e-test]
    if: always() && contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
